# Generated by Django 2.2.5 on 2020-12-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201120_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB')], default='RUB', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='ru', max_length=2),
        ),
    ]
